name: Run examlpes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy flake8 pycodestyle pytest nbval pandas minisom matplotlib scikit-learn
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Running notebooks with examples
      run: |
        pytest --nbval-lax examples/BasicUsage.ipynb
        pytest --nbval-lax examples/Clustering.ipynb
        pytest --nbval-lax examples/Classification.ipynb
        pytest --nbval-lax examples/ColorQuantization.ipynb
        pytest --nbval-lax examples/ColorSpaceMapping.ipynb
        pytest --nbval-lax examples/OutliersDetection.ipynb
        pytest --nbval-lax examples/TravellingSalesmanProblem.ipynb
        pytest --nbval-lax examples/HexagonalTopology.ipynb
        pytest --nbval-lax examples/HandwrittenDigits.ipynb
        pytest --nbval-lax examples/TimeSeries.ipynb
        pytest --nbval-lax examples/TopicModeling.ipynb
        pytest --nbval-lax examples/DemocracyIndex.ipynb
        
